--[[
	Define global money multipliers.
]]--

GLOBAL_MONEY_MULTIPLIER = 1
KILL_MONEY_MULTIPLIER = 1
BITCOIN_MONEY_MULTIPLIER = 1
CONTRACT_MONEY_MULTIPLIER = 1
BOUNTY_MONEY_MULTIPLIER = 1
SKIN_SPEED_MULTIPLIER = 1