print( "  \"" .. LocalWeapon():GetClass() .. "\": {" )
print( "    \"price\": FILLME," )
print( "    \"slot\": " .. ( 1 ) .. "," )
print( "    \"parent\": \"FILLME\"," )
print( "    \"deep\": FILLME," )
print( "    \"model\": \"" .. LocalWeapon().WorldModel .. "\"," )
print( "    \"basic\": FILLME," )
print( "    \"name\": \"" .. LocalWeapon().PrintName .. "\"" )
print( "  }" )